name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: aryan68125
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Check Current Git Config
        run: |
          git config --global user.name
          git config --global user.email

      - name: Echo token present
        run: echo "Token is present"
        env:
          TOKEN: ${{ secrets.SNAKE_PAT }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
          token: ${{ secrets.SNAKE_PAT }}   # ✅ this is correct

